version: "3"

services:
  app:
    build: .
    environment:
      DB_USER_NAME: root
      DB_PASSWORD: password
      DB_HOST_NAME: db
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - db-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - db-network
networks:
  db-network:
    driver: bridge
volumes:
  data-mysql:
